site_name: MaNGOS Playerbot Lua Scripting Documentation
site_url: https://example.com/

nav:
    - Home: index.md
    - API Reference: api.md

theme:
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - tables