name: client-ci 
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - run: pip install -r src/client/requirements.txt pyinstaller
    - run: pyinstaller --onefile src/client/playerbot.py
    - run: tar.exe -a -c -f dist/playerbot.zip dist/playerbot.exe

    - uses: softprops/action-gh-release@v1
      with:
        body_path: src/client/CHANGELOG.md
        files: dist/playerbot.zip
          